name: Setup Dhall
description: Install a Dhall version, including dhall-json, and provide the binary to run commands.
author: Craig Day
branding:
  color: blue
  icon: code

inputs:
  version:
    description: 'Version of Dhall to use. Default: `latest`'
    required: false
    default: latest

runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.version }}
