on: [push]

jobs:
  build:
    name: Print Versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          - 1.29.0
          - latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dhall
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Print version
        run: |
          echo "dhall version: $(dhall version)"
          echo "dhall-json version: $(dhall-to-json --version)"
